// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: comdex/ojooracle/v1beta1/tx.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgFetchPriceData struct {
	Creator            string              `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	SourceChannel      string              `protobuf:"bytes,3,opt,name=source_channel,json=sourceChannel,proto3" json:"source_channel,omitempty"`
	Calldata           *FetchPriceCallData `protobuf:"bytes,4,opt,name=calldata,proto3" json:"calldata,omitempty"`
	ExecuteGas         uint64              `protobuf:"varint,10,opt,name=execute_gas,json=executeGas,proto3" json:"execute_gas,omitempty"`
	ClientID           string              `protobuf:"bytes,11,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	TwaBatchSize       uint64              `protobuf:"varint,12,opt,name=twa_batch_size,json=twaBatchSize,proto3" json:"twa_batch_size,omitempty"`
	AcceptedHeightDiff int64               `protobuf:"varint,13,opt,name=accepted_height_diff,json=acceptedHeightDiff,proto3" json:"accepted_height_diff,omitempty" yaml:"accepted_height_diff"`
}

func (m *MsgFetchPriceData) Reset()         { *m = MsgFetchPriceData{} }
func (m *MsgFetchPriceData) String() string { return proto.CompactTextString(m) }
func (*MsgFetchPriceData) ProtoMessage()    {}
func (*MsgFetchPriceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fdd2bf419d61285, []int{0}
}
func (m *MsgFetchPriceData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFetchPriceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFetchPriceData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFetchPriceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFetchPriceData.Merge(m, src)
}
func (m *MsgFetchPriceData) XXX_Size() int {
	return m.Size()
}
func (m *MsgFetchPriceData) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFetchPriceData.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFetchPriceData proto.InternalMessageInfo

func (m *MsgFetchPriceData) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgFetchPriceData) GetSourceChannel() string {
	if m != nil {
		return m.SourceChannel
	}
	return ""
}

func (m *MsgFetchPriceData) GetCalldata() *FetchPriceCallData {
	if m != nil {
		return m.Calldata
	}
	return nil
}

func (m *MsgFetchPriceData) GetExecuteGas() uint64 {
	if m != nil {
		return m.ExecuteGas
	}
	return 0
}

func (m *MsgFetchPriceData) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *MsgFetchPriceData) GetTwaBatchSize() uint64 {
	if m != nil {
		return m.TwaBatchSize
	}
	return 0
}

func (m *MsgFetchPriceData) GetAcceptedHeightDiff() int64 {
	if m != nil {
		return m.AcceptedHeightDiff
	}
	return 0
}

type MsgFetchPriceDataResponse struct {
}

func (m *MsgFetchPriceDataResponse) Reset()         { *m = MsgFetchPriceDataResponse{} }
func (m *MsgFetchPriceDataResponse) String() string { return proto.CompactTextString(m) }
func (*MsgFetchPriceDataResponse) ProtoMessage()    {}
func (*MsgFetchPriceDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fdd2bf419d61285, []int{1}
}
func (m *MsgFetchPriceDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFetchPriceDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFetchPriceDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFetchPriceDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFetchPriceDataResponse.Merge(m, src)
}
func (m *MsgFetchPriceDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgFetchPriceDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFetchPriceDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFetchPriceDataResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgFetchPriceData)(nil), "comdex.ojooracle.v1beta1.MsgFetchPriceData")
	proto.RegisterType((*MsgFetchPriceDataResponse)(nil), "comdex.ojooracle.v1beta1.MsgFetchPriceDataResponse")
}

func init() { proto.RegisterFile("comdex/ojooracle/v1beta1/tx.proto", fileDescriptor_4fdd2bf419d61285) }

var fileDescriptor_4fdd2bf419d61285 = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x6b, 0x36, 0x41, 0xe7, 0x76, 0x93, 0xb0, 0x76, 0x30, 0x9b, 0x94, 0x96, 0x0a, 0xa4,
	0x82, 0x20, 0xd1, 0xd8, 0x8d, 0x63, 0x5b, 0xc1, 0x76, 0x98, 0x04, 0xe1, 0xc6, 0x25, 0x7a, 0x71,
	0x5e, 0x12, 0x23, 0x37, 0x8e, 0x62, 0x97, 0x75, 0xfb, 0x14, 0x7c, 0x2c, 0x8e, 0x3b, 0x72, 0x9a,
	0x50, 0xf3, 0x0d, 0xf8, 0x04, 0xc8, 0x49, 0xb6, 0x21, 0xb1, 0xdd, 0xe2, 0xdf, 0xfb, 0xc5, 0xef,
	0xf9, 0xff, 0xe8, 0x73, 0xa1, 0x97, 0x09, 0xae, 0x03, 0xfd, 0x4d, 0xeb, 0x0a, 0x84, 0xc2, 0xe0,
	0xfb, 0x51, 0x8c, 0x16, 0x8e, 0x02, 0xbb, 0xf6, 0xcb, 0x4a, 0x5b, 0xcd, 0x78, 0xab, 0xf8, 0xb7,
	0x8a, 0xdf, 0x29, 0x07, 0xfb, 0x99, 0xce, 0x74, 0x23, 0x05, 0xee, 0xab, 0xf5, 0x0f, 0x3c, 0xa1,
	0xcd, 0x52, 0x9b, 0x20, 0x06, 0x73, 0x77, 0x9b, 0xd0, 0xb2, 0xe8, 0xea, 0xaf, 0x1f, 0x6c, 0x99,
	0xa2, 0x15, 0x79, 0x54, 0x56, 0x52, 0x60, 0xeb, 0x4e, 0xea, 0x47, 0xf4, 0xe9, 0x99, 0xc9, 0x3e,
	0xb8, 0xc2, 0x27, 0xc7, 0x17, 0x60, 0x81, 0x71, 0xfa, 0x44, 0x54, 0x08, 0x56, 0x57, 0x9c, 0x8c,
	0xc9, 0x74, 0x27, 0xbc, 0x39, 0xb2, 0x97, 0x74, 0xcf, 0xe8, 0x55, 0x25, 0x30, 0x12, 0x39, 0x14,
	0x05, 0x2a, 0xbe, 0xd5, 0x08, 0xbb, 0x2d, 0x9d, 0xb7, 0x90, 0x9d, 0xd0, 0xbe, 0x00, 0xa5, 0x12,
	0xb0, 0xc0, 0xb7, 0xc7, 0x64, 0x3a, 0x78, 0xf7, 0xc6, 0x7f, 0xe8, 0x95, 0xfe, 0x5d, 0xf3, 0x39,
	0x28, 0xe5, 0x06, 0x08, 0x6f, 0xff, 0x66, 0x23, 0x3a, 0xc0, 0x35, 0x8a, 0x95, 0xc5, 0x28, 0x03,
	0xc3, 0xe9, 0x98, 0x4c, 0xb7, 0x43, 0xda, 0xa1, 0x8f, 0x60, 0xd8, 0x2b, 0xba, 0x23, 0x94, 0xc4,
	0xc2, 0x46, 0x32, 0xe1, 0x03, 0x37, 0xcc, 0x6c, 0xb8, 0xb9, 0x1e, 0xf5, 0xe7, 0x0d, 0x3c, 0x5d,
	0x84, 0xfd, 0xb6, 0x7c, 0x9a, 0xb0, 0x17, 0x74, 0xcf, 0x9e, 0x43, 0x14, 0x83, 0x4b, 0xc1, 0xc8,
	0x4b, 0xe4, 0xc3, 0xe6, 0xba, 0xa1, 0x3d, 0x87, 0x99, 0x83, 0x5f, 0xe4, 0x25, 0xb2, 0xcf, 0x74,
	0x1f, 0x84, 0xc0, 0xd2, 0x62, 0x12, 0xe5, 0x28, 0xb3, 0xdc, 0x46, 0x89, 0x4c, 0x53, 0xbe, 0x3b,
	0x26, 0xd3, 0xad, 0xd9, 0xe8, 0xcf, 0xf5, 0xe8, 0xf0, 0x02, 0x96, 0xea, 0xfd, 0xe4, 0x3e, 0x6b,
	0x12, 0xb2, 0x1b, 0x7c, 0xd2, 0xd0, 0x85, 0x83, 0x87, 0xf4, 0xd9, 0x7f, 0x21, 0x87, 0x68, 0x4a,
	0x5d, 0x18, 0x9c, 0x9d, 0xfd, 0xdc, 0x78, 0xe4, 0x6a, 0xe3, 0x91, 0xdf, 0x1b, 0x8f, 0xfc, 0xa8,
	0xbd, 0xde, 0x55, 0xed, 0xf5, 0x7e, 0xd5, 0x5e, 0xef, 0xeb, 0x71, 0x26, 0x6d, 0xbe, 0x8a, 0x5d,
	0x72, 0x41, 0x9b, 0xde, 0x5b, 0x9d, 0xa6, 0x52, 0x48, 0x50, 0xdd, 0x39, 0xf8, 0x77, 0xcb, 0xf6,
	0xa2, 0x44, 0x13, 0x3f, 0x6e, 0x16, 0x7b, 0xfc, 0x37, 0x00, 0x00, 0xff, 0xff, 0xd1, 0xf7, 0x13,
	0x70, 0x79, 0x02, 0x00, 0x00,
}

func (m *MsgFetchPriceData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFetchPriceData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFetchPriceData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AcceptedHeightDiff != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.AcceptedHeightDiff))
		i--
		dAtA[i] = 0x68
	}
	if m.TwaBatchSize != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TwaBatchSize))
		i--
		dAtA[i] = 0x60
	}
	if len(m.ClientID) > 0 {
		i -= len(m.ClientID)
		copy(dAtA[i:], m.ClientID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ClientID)))
		i--
		dAtA[i] = 0x5a
	}
	if m.ExecuteGas != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ExecuteGas))
		i--
		dAtA[i] = 0x50
	}
	if m.Calldata != nil {
		{
			size, err := m.Calldata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.SourceChannel) > 0 {
		i -= len(m.SourceChannel)
		copy(dAtA[i:], m.SourceChannel)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourceChannel)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgFetchPriceDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFetchPriceDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFetchPriceDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgFetchPriceData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SourceChannel)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Calldata != nil {
		l = m.Calldata.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ExecuteGas != 0 {
		n += 1 + sovTx(uint64(m.ExecuteGas))
	}
	l = len(m.ClientID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.TwaBatchSize != 0 {
		n += 1 + sovTx(uint64(m.TwaBatchSize))
	}
	if m.AcceptedHeightDiff != 0 {
		n += 1 + sovTx(uint64(m.AcceptedHeightDiff))
	}
	return n
}

func (m *MsgFetchPriceDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgFetchPriceData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFetchPriceData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFetchPriceData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceChannel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceChannel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Calldata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Calldata == nil {
				m.Calldata = &FetchPriceCallData{}
			}
			if err := m.Calldata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecuteGas", wireType)
			}
			m.ExecuteGas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExecuteGas |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TwaBatchSize", wireType)
			}
			m.TwaBatchSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TwaBatchSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcceptedHeightDiff", wireType)
			}
			m.AcceptedHeightDiff = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AcceptedHeightDiff |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFetchPriceDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFetchPriceDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFetchPriceDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
